// <auto-generated />
using System;
using LLLMax.Api.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLLMax.Api.Storage.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260508191854_AddAssistantIdentityToUserProfile")]
    partial class AddAssistantIdentityToUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LLLMax.Api.Storage.ApiIntegrationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("discovered_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OpenApiUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("open_api_url");

                    b.Property<string>("OperationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operations_json");

                    b.Property<string>("RawSchema")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_schema");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("api_integrations", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.AppMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_metadata", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.ApprovalEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.BackgroundJobArtifactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobId");

                    b.ToTable("background_job_artifacts", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.BackgroundJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<bool>("NotifySession")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notify_session");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProgressCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress_current");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress_total");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_message");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("background_jobs", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.DocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_file_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.McpServerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("transport");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("mcp_servers", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.McpToolEntity", b =>
                {
                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_status");

                    b.Property<string>("ArgumentsJsonSchema")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments_json_schema");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ServerId", "Name");

                    b.ToTable("mcp_tools", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.MemoryConsolidationJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<int>("MemoriesWritten")
                        .HasColumnType("INTEGER")
                        .HasColumnName("memories_written");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("TaskGraphId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_graph_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("memory_consolidation_jobs", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("agent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.SessionMessageEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("CitationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("citations_json");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("ReasoningStepsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasoning_steps_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("TaskGraphJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_graph_json");

                    b.Property<string>("ToolTracesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_traces_json");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("trace_id");

                    b.HasKey("SessionId", "Ordinal");

                    b.ToTable("session_messages", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.TaskGraphEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActiveNodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_node_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("goal");

                    b.Property<string>("GraphJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("graph_json");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("task_graphs", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.UserProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssistantDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assistant_description");

                    b.Property<string>("AssistantName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assistant_name");

                    b.Property<string>("CommunicationStyle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("communication_style");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("constraints");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Facts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("facts");

                    b.Property<string>("FamilyAndRelations")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("family_and_relations");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("goals");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("interests");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("Work")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("work");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("LLLMax.Api.Storage.McpToolEntity", b =>
                {
                    b.HasOne("LLLMax.Api.Storage.McpServerEntity", "Server")
                        .WithMany("Tools")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("LLLMax.Api.Storage.SessionMessageEntity", b =>
                {
                    b.HasOne("LLLMax.Api.Storage.SessionEntity", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LLLMax.Api.Storage.McpServerEntity", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("LLLMax.Api.Storage.SessionEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
